### PR TITLE
Cache prefixes in memory

### PR DESCRIPTION
**Pull request by UnsignedArduino**

### CODE REVIEW

**Comment by Shinyzenith** [comment]
Let make a guildprefixmanager file and class separate from guild config manager, set add and list prefixes can be in guildconfigmanager however.

**Comment by UnsignedArduino** [comment]
But I think we should have just one class manage getting and setting the prefixes and that class will do the LRU caching so then we can clear the cache items when the prefixes change easily.

**Comment by Shinyzenith** [comment]
Ok that works.

**Comment by UnsignedArduino** [comment]
Please note that the GuildConfigManager **is now a singleton**, so everytime you make a new one it just returns you the old one. It does not seem like it would break anything, but I wanted to let you know. I've only tested the prefixes adding and removing and using some commands like `ping` and `goose`.

**Pull request merged**
