### PR TITLE
add default reason for moderator actions, allow unmuting users with no mutes logged

### PR DESCRIPTION
**Pull request by thurm64**

### CODE REVIEW

**Comment by thurm64** [comment]
oops, reverting this back to the old state

**Comment by thurm64** [comment]
Okay, it's back to how it was before *facepalm*

**Comment by actualdankcoder** [comment]
Could you provide test screenshots of these changes

**Comment by Shinyzenith** [comment]
@thurm64 Can you please provide screenshots of your changes?

**Comment by thurm64** [comment]
Sure thing! Sorry about the mess of commits I created, git is hard :|

Messsage and functionality of unmuting a user who was given the mute role without the bot:
erin-webhooks - Discord 7_7_2021 2_01_51 PM

Mute with no reason:
screenshot - Discord 7_7_2021 2_05_25 PM

Punishment log with the default reason:
screenshot - Discord 7_7_2021 2_04_48 PM

**Comment by Shinyzenith** [comment]
About line 992, please make sure all user warns objects dm the following format unknown

and for mutes that were not logged while erin was online, please log those and don't dm the user the data. (aka the if check which spits out "uhhh awkward moment" message , that should log the mute with no reason for the user)

if possible please also integrate a listener which checks if a role was added to any member and if it's the mute role or not, then we can auto log it (this will essentially log the mutes of other bots too)

**Comment by Shinyzenith** [comment]
I'll merge this for now, but please do make the changes i mentioned here in a separate PR

**Pull request merged**
