### PR TITLE
Add stocks command

### PR DESCRIPTION
**Pull request by thurm64**
I added a command that uses the polygon.io API to retrieve stock data. 

I put the polygon.io API key in the code since the API is free and doesn't have a ratelimit, so there's really no way that it would cause any problems, but if it needs to be changed the website is [here](http://polygon.io).

stocks command image

### CODE REVIEW

**Review by actualdankcoder — CHANGES_REQUESTED** [review]
The api key for this could be stored in the env file over the code itself

**Comment by thurm64** [comment]
Alright, makes sense, I'm new to discord bots in python (i've done discord.js and regular python before) so i wasn't sure about best practices

**Comment by thurm64** [comment]
Alright, should be fixed now, and also made a few improvements to the functionality as well.

**Review by actualdankcoder — CHANGES_REQUESTED** [review]
just leave the space blank in demo.env, like the other keys

**Review by actualdankcoder — APPROVED** [review]

**Comment by thurm64** [comment]
ah, okay my bad

**Comment by thurm64** [comment]
cool! thanks for the help, I'll be working on some more stuff soon

**Pull request merged**
