### PR TITLE
Add image manipulation cog

### PR DESCRIPTION
**Pull request by thurm64**
This is the start of what I plan on making a much larger project. All commands are documented in the code.

### CODE REVIEW

**Comment by thurm64** [comment]
There are a lot of commands, but if you want i can provide screenshots

**Comment by Shinyzenith** [comment]
Keep developing this PR, I'll push to prod when there's a few more commands. 
Take all the time you need

**Comment by Shinyzenith** [comment]
This bot no longer has any integration with the mattias krantz discord server 😄 feel free to edit out those commits.

**Comment by thurm64** [comment]
bro
sad

**Comment by thurm64** [comment]
ok done

**Pull request merged**
