### PR TITLE
Changes to delpunishments command

### PR DESCRIPTION
**Pull request by thurm64**
Command now uses a message reply instead of a reaction.

### CODE REVIEW

**Review by Shinyzenith — CHANGES_REQUESTED** [review]
Please change the 100y argument in mute command, that task has been assigned to my board along with a custom async handler for it.

I'll be coding out that part. Thanks in advance.

**Comment by Shinyzenith** [comment]
I'm also gonna assume that you've tested the message confirmation ? if yes then i'll push to prod directly.

**Review by Shinyzenith — CHANGES_REQUESTED** [review]
Set mute_period to str , I asked to just remove the 100y.

**Comment by thurm64** [comment]
done

**Pull request merged**
